version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "${MINIOPORT}:9090"
      - "${MINIOADMPORT}:9091"
    restart: on-failure
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address :9091 --address :9090 /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/minio/health/live"]
      interval: 5s
      timeout: 20s
      retries: 3

